name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código
        uses: actions/checkout@v4.1.3
      - name: Autenticação Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.6.1
        with:       
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            1df9840472ec/bootcamp-microsservises${{ github.run_number }}
            1df9840472ec/bootcamp-microsservises:latest

          
    
